### ISSUE TITLE
Where do we copy our current profile

### ISSUE THREAD

**Issue by bonelifer** [charmparticle/ffupdate#2]
Where do we copy our current profile so that this install uses it? I'm getting tired of the snap version of FF not working with keepassxc. Also from the readme, is it true that setting the permissions on /opt/mozilla will all this install to update itself?

**Comment by bonelifer** [comment]
So used the good old config:support, like I should of to begin with an am now back to using keepassxc with Firefox. Thanks for the easy to use script.

**Comment by charmparticle** [comment]
> is it true that setting the permissions on /opt/mozilla will all this install to update itself?

Yes: you can do a `chown -R bonelifer:bonelifer /opt/mozilla` (or whatever your username is on your system), and from then on, you can update firefox or thunderbird from within the app. It took me way too long to realize this.

**Comment by bonelifer** [comment]
Would you be interested in an updated version that will get the users username,primary_group and set the permissions for the destination if an optional parameter is passed?  I got bored and have been playing around with ChatGPT. If so, then I can fork and do a PR.
